version: '3'

name: factorio-blueprints
services:
  app:
    container_name: app
    image: node:20.18-alpine
    working_dir: /app
    env_file: ../.env
    ports:
      - 3000:3000
    depends_on:
      - firebase-emulator
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ..:/app

  firebase-emulator:
    container_name: firebase-emulator
    image: andreysenov/firebase-tools:latest-node-20-slim
    build:
      context: ../.firebase
    tty: true
    volumes:
      - ../.firebase:/home/node
    ports:
      - 9099:9099 # AUTH_PORT
      - 4000:4000 # UI_PORT
      - 5001:5001 # CLOUD FUNCTIONS
      - 9005:9005 # LOGIN PORT
      